name: easy_web_view
description: A super simple webview for Flutter Web, Mobile and Desktop
version: 1.6.0
homepage: https://github.com/rodydavis/easy_web_view
repository: https://github.com/rodydavis/plugins
maintainer: Rody Davis (@rodydavis)
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_markdown: ^0.7.1
  flutter_widget_from_html: ^0.15.0
  html2md: ^1.2.5
  http: ^1.2.0
  markdown: ^7.1.1
  permission_handler: ^11.3.1
  url_launcher: ^6.1.9
  webview_flutter: ^4.0.2
  webview_windows: ^0.4.0

  webview_flutter_wkwebview: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
